In [1]:
list1=[10,20,30]
list2=[50,60,70]
print(list1+list2)

[10, 20, 30, 50, 60, 70]


In [43]:
import numpy as np
list1=np.array([10,20,30])
list2=np.array([50,60,70])
print(list1+list2)

[ 60  80 100]


In [2]:
import numpy as np
list1= np.array([10,20,30])
list2= np.array([50,60,70])
print( np.concatenate([list1,list2]))


[10 20 30 50 60 70]


In [4]:
a=np.array([20,30,40])
b=np.array([5])
print(a*b)

[100 150 200]


In [5]:
dimen2=np.array([[1,2,3],[20,30,40]])
print(dimen2)

[[ 1  2  3]
 [20 30 40]]


In [13]:
dimen2=np.array([[1,2,3],[20,30,40],[40,50,60]])
print(dimen2[0:3,0:2])


[[ 1  2]
 [20 30]
 [40 50]]


In [85]:
dimen2=np.array([[1,2,3],[20,30,40],[40,50,60]])
print(np.shape(dimen2))
print(np.size(dimen2))
print(np.ndim(dimen2))#rows and colums 2d ke hai 
print(dimen2.dtype)
print(len(dimen2))
print()
print(dimen2.astype(float))

(3, 3)
9
2
int64
3

[[ 1.  2.  3.]
 [20. 30. 40.]
 [40. 50. 60.]]


In [20]:
import numpy as np
a=[10,20,30,40,50]
b=[60,70,80,90,100]
print(np.add(a,b))  


[ 70  90 110 130 150]


In [83]:
import numpy as np
a=[[10,20],[40,50]]
b=[[60,70],[90,100]]
print(np.add(a,b))
print()
print(np.subtract(a,b)) 



[[ 70  90]
 [130 150]]

[[-50 -50]
 [-50 -50]]


In [31]:
a=[10,20,30,40,50]
b=[6]
print(np.power(a,b))  

[    1000000    64000000   729000000  4096000000 15625000000]


In [33]:
a=[9,81,225,625]
print(np.sqrt(a)  )

[ 3.  9. 15. 25.]


In [84]:
import numpy as np
list1= np.array([[10,20],[30,40]])
list2= np.array([[50,60],[70,80]])

print( np.concatenate([list1,list2],axis =1 ) )
print()
print( np.concatenate([list1,list2],axis =0 ) )
print()
print( np.hstack([list1,list2]) )          
print()
print( np.vstack([list1,list2]) )          

[[10 20 50 60]
 [30 40 70 80]]

[[10 20]
 [30 40]
 [50 60]
 [70 80]]

[[10 20 50 60]
 [30 40 70 80]]

[[10 20]
 [30 40]
 [50 60]
 [70 80]]


In [86]:
import numpy as np
list1= np.array([[10,20],[30,40]])

print(np.append(list1,[90,20]))
print()
print(np.insert(list1,1,200))
print()
print(np.insert(list1,1,[50,60],axis=1))
print()
print(np.insert(list1,1,[50,60],axis=0))  
print()
print(np.insert(list1,1,[50],axis=0))   

[10 20 30 40 90 20]

[ 10 200  20  30  40]

[[10 50 20]
 [30 60 40]]

[[10 20]
 [50 60]
 [30 40]]

[[10 20]
 [50 50]
 [30 40]]


In [63]:
a=[1,2,3,4,5,6,7,8]
print(np.delete(a,2))

[1 2 4 5 6 7 8]


In [66]:
#sort filter and search

arr=np.array([3,5,2,6,4,9,7,1])
print(np.sort(arr))

[1 2 3 4 5 6 7 9]


In [69]:
arr=np.array([[3,5,2,6,4,9,7,1],[1,5,3,9,6,2,3,0]])
print(np.sort(arr))

[[1 2 3 4 5 6 7 9]
 [0 1 2 3 3 5 6 9]]


In [70]:
arr=np.array([3,5,2,6,4,9,7,1])
s=np.searchsorted(arr,4)
print(s)

3


In [3]:
#aggregeting in array

import numpy as np
a=np.array([10,20,30,40,50])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.size(a))
print(np.cumsum(a))             

150
10
50
5
[ 10  30  60 100 150]


In [91]:
a=[100,200,300,400,500]
b=[10,20,30,40,50]
price=np.array(a)
quantity=np.array(b)
print(price,"\n",quantity)
print()
print(np.cumprod([price,quantity],axis=0))
print()
print(np.sum(price))

[100 200 300 400 500] 
 [10 20 30 40 50]

[[  100   200   300   400   500]
 [ 1000  4000  9000 16000 25000]]

1500


In [97]:
#statistical function in array
import numpy as np
import statistics as stats
baked_food=[200,300,150,130,200,280,170,188]
print(np.mean(baked_food))                
print(np.median(baked_food))                
print(stats.mode(baked_food))              
print(np.std(baked_food))           
print(np.var(baked_food))           

202.25
194.0
200
55.68157235567257
3100.4375


In [99]:

tobocco_cumsumption=[30,50,10,40,60]
deaths=[100,120,30,150,80]
print(np.corrcoef([tobocco_cumsumption,deaths]))


[[1.         0.53654243]
 [0.53654243 1.        ]]


In [102]:

sale=[300,100,350,150]
price=[10,20,7,17]
print(np.corrcoef([sale,price]))



[[ 1.         -0.99892009]
 [-0.99892009  1.        ]]
